### ISSUE TITLE
Css are missing after npm run development

### ISSUE THREAD

**Issue by askides** [GusZandy/laravel-tabler#6]
Hi!
I've tried to install the package. All was correct until i've done
`npm run development`
This command not return error, the compilation goes success, but if i reload the page the tabler.css file is filled with some JS..

Anyone has the same problem? 

Renny

**Comment by frdteknikelektro** [comment]
Yes, I've check it, this package setup doesn't support laravel-mix@^4.0 . Try to downgrade laravel mix

```
npm install laravel-mix@^3.0 --save-dev
```

**Comment by askides** [comment]
Thanks @frdteknikelektro!
This Workaround works! :)
